name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    name: Test Java ${{ matrix.java }} (${{ matrix.os }})
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        exclude:
          - java: '8'
            os: 'macos-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build Java ${{ matrix.java }} (${{ matrix.os }})
        run: ./gradlew -p java :java:value-types:build
      - name: Test  Java ${{ matrix.java }} (${{ matrix.os }})
        run: ./gradlew -p java :java:value-types-test${{ matrix.java }}:check